### ISSUE TITLE
Unicorn + Octopus config conflict

### ISSUE THREAD

**Issue by noff** [tchandy/octopus#174]
We have this config in unicorn:

```
before_fork do |server, worker|
  ActiveRecord::Base.connection.disconnect!
  old_pid = "#{server.config[:pid]}.oldbin"
  if File.exists?(old_pid) && server.pid != old_pid
    begin
      Process.kill("QUIT", File.read(old_pid).to_i)
    rescue Errno::ENOENT, Errno::ESRCH
    end
  end
end
```

When verify_connection is enabled in octopus config:
```
octopus:
  verify_connection: true
```

Then unicorn throws exception on start

```
I, [2013-06-10T17:52:59.207223 #31459]  INFO -- : Refreshing Gem list
I, [2013-06-10T17:53:09.831291 #31459]  INFO -- : unlinking existing socket=/var/www/myproject/shared/sockets/unicorn.sock
I, [2013-06-10T17:53:09.831616 #31459]  INFO -- : listening on addr=/var/www/myproject/shared/sockets/unicorn.sock fd=13
I, [2013-06-10T17:53:09.835338 #31459]  INFO -- : master process ready
I, [2013-06-10T17:53:09.852287 #31466]  INFO -- : worker=0 ready
I, [2013-06-10T17:53:31.709293 #31459]  INFO -- : reaped #<Process::Status: pid 31466 exit 0> worker=0
I, [2013-06-10T17:53:31.709486 #31459]  INFO -- : master complete
I, [2013-06-10T17:53:54.511064 #31643]  INFO -- : Refreshing Gem list
I, [2013-06-10T17:54:05.183939 #31643]  INFO -- : unlinking existing socket=/var/www/myproject/shared/sockets/unicorn.sock
I, [2013-06-10T17:54:05.184235 #31643]  INFO -- : listening on addr=/var/www/myproject/shared/sockets/unicorn.sock fd=13
E, [2013-06-10T17:54:05.188349 #31643] ERROR -- : connection is closed (PG::Error)
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:351:in `reset'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:351:in `reconnect!'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:219:in `verify!'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:171:in `block (2 levels) in verify_active_connections!'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:170:in `each'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:170:in `block in verify_active_connections!'
/usr/local/rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:168:in `verify_active_connections!'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:143:in `select_connection'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:215:in `method_missing'
config/unicorn.rb:19:in `block in reload'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.0/lib/unicorn/http_server.rb:495:in `call'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.0/lib/unicorn/http_server.rb:495:in `spawn_missing_workers'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.0/lib/unicorn/http_server.rb:142:in `start'
/var/www/myproject/shared/bundle/ruby/1.9.1/gems/unicorn-4.6.0/bin/unicorn:126:in `<top (required)>'
/var/www/myproject/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `load'
/var/www/myproject/shared/bundle/ruby/1.9.1/bin/unicorn:23:in `<main>'
```

But if disable verify_connection directive, all works OK.

**Comment by sobrinho** [comment]
Please check #59. I would accept a pull request documenting that or you can create a wiki page like using octopus with unicorn :)
