### ISSUE TITLE
rake db:migrate:reset is not working with octopus replication enabled

### ISSUE THREAD

**Issue by vishakhasawant** [tchandy/octopus#179]
I am using octopus 0.5.0 and rails 3.1.10, pg 0.12.2 version. I created a minimal app to reproduce this issue with one migration. It also throws the same exception.
Detailed stack trace of the same.
```ruby
NOTICE:  database "octopus_replication_1" does not exist, skipping
NOTICE:  database "octopus_replication_test" does not exist, skipping
octopus_replication_1 already exists
octopus_replication_test already exists
rake aborted!
FATAL:  database "octopus_replication_1" does not exist
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:1208:in `initialize'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:1208:in `new'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:1208:in `connect'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:326:in `initialize'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `new'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `postgresql_connection'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:153:in `select_connection'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:215:in `method_missing'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/migration.rb:662:in `initialize'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/migration.rb:570:in `new'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/migration.rb:570:in `up'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/migration.rb:122:in `up_with_octopus'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/migration.rb:551:in `migrate'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/migration.rb:116:in `block in migrate_with_octopus'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:171:in `run_queries_on_shard'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:180:in `block in send_queries_to_multiple_shards'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:179:in `each'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/proxy.rb:179:in `send_queries_to_multiple_shards'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/ar-octopus-0.5.0/lib/octopus/migration.rb:115:in `migrate_with_octopus'
/usr/local/rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.11/lib/active_record/railties/databases.rake:179:in `block (2 levels) in <top (required)>'

```

**Comment by sobrinho** [comment]
Closing due to lack of movement but I would be happy to inspect if this is still an issue for you. Please test against fixing_db_prepare branch if that's the case.

**Comment by adkron** [comment]
I currently have this problem, and it looks like the tasks that you have in the branch work for me, but I have to remove `if Octopus.rails32?` since it doesn't exist. I tested the `lib/tasks/activerecord.rake` file with ar-octopus 0.8.6.
