### ISSUE TITLE
Rails 4.2.0.beta1 is not supported

### ISSUE THREAD

**Issue by pawelkomarnicki** [tchandy/octopus#273]
Following this guide: https://github.com/tchandy/octopus/wiki/Replication-with-Rails-on-Heroku

When running `rake test` I get `ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  cannot drop the currently open database`:

```bash
rake test
=> 2 databases enabled as read-only slaves
  * FOLLOWER 1
  * FOLLOWER 2
rake aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  cannot drop the currently open database
: DROP DATABASE IF EXISTS "jacky_test"
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:458:in `block in log'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bundler/gems/octopus-151ff3575d9d/lib/octopus/abstract_adapter.rb:15:in `instrument'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:452:in `log'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:92:in `drop_database'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bundler/gems/octopus-151ff3575d9d/lib/octopus/proxy.rb:270:in `method_missing'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/postgresql_database_tasks.rb:30:in `drop'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/postgresql_database_tasks.rb:43:in `purge'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:159:in `purge'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:201:in `load_schema_for'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:216:in `block in load_schema_current'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:255:in `block in each_current_configuration'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:254:in `each'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:254:in `each_current_configuration'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:215:in `load_schema_current'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:402:in `load_schema_if_pending!'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:409:in `block in maintain_test_schema!'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:637:in `suppress_messages'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:414:in `method_missing'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:409:in `maintain_test_schema!'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_help.rb:19:in `<top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/Sites/jacky-backend/test/test_helper.rb:9:in `<top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/Sites/jacky-backend/test/helpers/application_helper_test.rb:1:in `<top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
PG::ObjectInUse: ERROR:  cannot drop the currently open database
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:458:in `block in log'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bundler/gems/octopus-151ff3575d9d/lib/octopus/abstract_adapter.rb:15:in `instrument'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/abstract_adapter.rb:452:in `log'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:92:in `drop_database'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bundler/gems/octopus-151ff3575d9d/lib/octopus/proxy.rb:270:in `method_missing'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/postgresql_database_tasks.rb:30:in `drop'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/postgresql_database_tasks.rb:43:in `purge'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:159:in `purge'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:201:in `load_schema_for'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:216:in `block in load_schema_current'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:255:in `block in each_current_configuration'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:254:in `each'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:254:in `each_current_configuration'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/tasks/database_tasks.rb:215:in `load_schema_current'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:402:in `load_schema_if_pending!'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:409:in `block in maintain_test_schema!'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:637:in `suppress_messages'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:414:in `method_missing'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.0.beta1/lib/active_record/migration.rb:409:in `maintain_test_schema!'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_help.rb:19:in `<top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/Sites/jacky-backend/test/test_helper.rb:9:in `<top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/Sites/jacky-backend/test/helpers/application_helper_test.rb:1:in `<top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `block in require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:233:in `load_dependency'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.0.beta1/lib/active_support/dependencies.rb:248:in `require'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/gems/railties-4.2.0.beta1/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/pawelkomarnicki/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test:run => test:units
```

**Comment by tchandy** [comment]
Since Octopus already works on Rails 4.2, I'm closing this issue.

Thiago

**Comment by leonelgalan** [comment]
I'm on 4.2.3 and still seeing this issue. I successfully ran `rake octopus:copy_schema_versions` (so the shard migrations table is up-to-date and only the new migration runs), `rake db:migrate` created the new table in the shard. I can manipulate objects in shard using the `rails console`, but when I run tests:

```
 $ bin/rspec
rake aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  cannot drop the currently open database
: DROP DATABASE IF EXISTS "stealz_test"

PG::ObjectInUse: ERROR:  cannot drop the currently open database

Tasks: TOP => db:test:load => db:test:purge
(See full trace by running task with --trace)
```

**Comment by sgrif** [comment]
The upstream change was reverted in
https://github.com/rails/rails/commit/557c46a41ec73c485a783b56fbbe893a00f49fe8

**Comment by leonelgalan** [comment]
@tchandy, we should reopen this issue. I'll start looking for workarounds we can post here, until we find a permanent solution.

**Comment by randomm** [comment]
I'm experiencing this with Rails 4.2.2  and Octopus 0.8.5 

@leonelgalan did you figure out a workaround?

**Comment by randomm** [comment]
I monkeypatched rake db:schema:load for it to work as in the commit above.

```
require 'active_record'
Rake::Task['db:schema:load'].clear

namespace :db do
  namespace :schema do
    desc 'Load a schema.rb file into the database'
    task :load => [:load_config] do
      ActiveRecord::Tasks::DatabaseTasks.load_schema_current(:ruby, ENV['SCHEMA'])
    end
  end
end
```
Unfortunately no change to the actual issue I'm experiencing...

**Comment by jeremymarc** [comment]
same issue here
