### ISSUE TITLE
Problem with rake db:create db:migrate

### ISSUE THREAD

**Issue by snisarg** [tchandy/octopus#341]
I have slaves configured in the shards.xml file.
I get an error like this when I do rake db:create db:migrate:

$ rake db:create db:migrate
rake aborted!
ActiveRecord::ConnectionNotEstablished: ActiveRecord::ConnectionNotEstablished
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:205:in `safe_connection'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:212:in `select_connection'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:273:in `method_missing'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:913:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `new'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/migration.rb:110:in `up_with_octopus'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/migration.rb:104:in `block in migrate_with_octopus'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:226:in `block (2 levels) in run_queries_on_shard'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:476:in `using_shard'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:225:in `block in run_queries_on_shard'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:462:in `keeping_connection_proxy'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:224:in `run_queries_on_shard'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:233:in `block in send_queries_to_multiple_shards'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:232:in `each'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/proxy.rb:232:in `send_queries_to_multiple_shards'
/Library/Ruby/Gems/2.0.0/gems/ar-octopus-0.8.5/lib/octopus/migration.rb:103:in `migrate_with_octopus'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by luki3k5** [comment]
Hello, is there anybody who had a similar issue? Perhaps you manage to solve it @snisarg? Please let us know, we are currently stuck with a very same problem. Cheers.

**Comment by snisarg** [comment]
@luki3k5 I solved this problem on my side by calling db:create and then db:migrate, meaning calling them separately.

**Comment by sevaorlov** [comment]
we have the same problem
